---
title: "SupplAI"
author: "Farid Azouaou"
output: 
  flexdashboard::flex_dashboard:
    social: menu
    theme: 
      version: 4
      bootswatch: minty
---

```{r setup, include=FALSE,warning=FALSE,message=FALSE}
library("SupplAI")
library("flexdashboard")

db_con <- open_warehouse_db()
sc_meta_data <- load_db_metadata()
target_value_vars <- "sales"
date_var    <- "date"
as_of_date <- as.Date("2022-07-08")
target_item_ID <- "BREAD/BAKERY"
target_store_ID <- 4

```


Overview
=====================================

Inventory
=====================================  

## Column {data-width="500"}

### Demand Forecast

```{r demand_forecast,fig.width=200}
demand_forecast <- load_sales_forecasts(db_con = db_con, item_IDs = target_item_ID, 
                           store_IDs = target_store_ID,as_of_date = as_of_date,sc_meta_data = sc_meta_data, date_freq = NULL, fcast_horizon =  20)

demand_forecast%>%dplyr::group_by(as_of_date,date)%>%
        dplyr::summarise_at(c("forecast",  "upper",   "lower"),sum)%>%
        generate_sales_forecast_chart(target_variable = Sys.getenv("MONGODB_API_KEY1"))
```

```{r safety_stock,fig.width=150}

# gauge(42, min = 0, max = 100, symbol = '%', gaugeSectors(
#   success = c(80, 100), warning = c(40, 79), danger = c(0, 39)
# ))
#create_gauge_chart()

```

### Projected Inventory

```{r projected_inventory}
pv_params <- load_replenishemnt_parameters(db_con = db_con , item_ID = target_item_ID,
                                    store_ID = target_store_ID, sc_meta_data = sc_meta_data)

projected_inventory <- demand_forecast%>%
        calculate_projected_inventory_main(
          safety_stock = pv_params$safety_stock, 
          supply_freq = pv_params$supply_freq,
          projection_horizon = pv_params$forecast_horizon)
projected_inventory_chart <- projected_inventory%>%
  generate_projected_inventory_chart()

projected_inventory_chart

```


## Column {.tabset data-width="500"}


### Replenishment Strategy

```{r replenishment_strategy, fig.keep='none'}

grad_col_var <- c("demand_fcast","drp_amount","projected_inventory")
names(grad_col_var) <- c("#1B9E77","#D95F02","#E6AB02")
projected_inventory%>%
        display_dt_table_DT(grad_col_var = grad_col_var)
```

### Supply 

```{r supply, fig.keep='none'}

grad_col_var <- c("demand_fcast","drp_amount","projected_inventory")
names(grad_col_var) <- c("#1B9E77","#D95F02","#E6AB02")
projected_inventory%>%
        display_dt_table_DT(grad_col_var = grad_col_var)
```

